/*
  Unregelmäßige Verben (Englisch) für den Bereich „Grammatik“ – aus dem Schulbuch, Seite 206/207 „Irregular verbs“.

  Eintrag: [Infinitiv, simple past, past participle, Deutsch]
  - Eine von mehreren Formen reicht:   'burnt|burned'
  - Beide Formen gehören dazu:         'was/were'  (nur eine getippt → „fast richtig“, zweiter Versuch)
  - Klammern sind freiwillig:          'dealt (with)'  (auch „dealt“ allein ist richtig)
  - Der Fortschrittsschlüssel ist en|v|<Infinitiv ohne Klammern und Leerzeichen> (z. B. en|v|wakeup):
    den Infinitiv also nicht mehr ändern. Neue Verben einfach unten anhängen.
*/
window.VERBEN_EN = [
  ['be', 'was/were', 'been', 'sein'],
  ['beat', 'beat', 'beaten', 'schlagen; besiegen'],
  ['become', 'became', 'become', 'werden'],
  ['begin', 'began', 'begun', 'beginnen; anfangen'],
  ['bet', 'bet', 'bet', 'wetten'],
  ['bite', 'bit', 'bitten', 'beißen'],
  ['break', 'broke', 'broken', '(zer)brechen; kaputt machen'],
  ['bring', 'brought', 'brought', '(mit)bringen'],
  ['build', 'built', 'built', 'bauen'],
  ['burn', 'burnt|burned', 'burnt|burned', '(ver)brennen'],
  ['buy', 'bought', 'bought', 'kaufen'],
  ['catch', 'caught', 'caught', 'fangen'],
  ['choose', 'chose', 'chosen', '(aus)wählen'],
  ['come', 'came', 'come', 'kommen'],
  ['cost', 'cost', 'cost', 'kosten'],
  ['cut', 'cut', 'cut', 'schneiden'],
  ['deal (with)', 'dealt (with)', 'dealt (with)', 'sich befassen (mit); umgehen (mit)'],
  ['do', 'did', 'done', 'machen; tun'],
  ['draw', 'drew', 'drawn', 'zeichnen; ziehen'],
  ['dream', 'dreamt|dreamed', 'dreamt|dreamed', 'träumen'],
  ['drink', 'drank', 'drunk', 'trinken'],
  ['drive', 'drove', 'driven', 'fahren'],
  ['eat', 'ate', 'eaten', 'essen'],
  ['fall', 'fell', 'fallen', '(hin)fallen'],
  ['feed', 'fed', 'fed', 'füttern; ernähren'],
  ['feel', 'felt', 'felt', 'fühlen'],
  ['fight', 'fought', 'fought', 'kämpfen; (sich) streiten'],
  ['find', 'found', 'found', 'finden'],
  ['fit', 'fit|fitted', 'fit|fitted', 'passen'],
  ['fly', 'flew', 'flown', 'fliegen'],
  ['forget', 'forgot', 'forgotten', 'vergessen'],
  ['forgive', 'forgave', 'forgiven', 'vergeben; verzeihen'],
  ['freeze', 'froze', 'frozen', 'gefrieren; erstarren'],
  ['get', 'got', 'got', 'bekommen; erhalten'],
  ['give', 'gave', 'given', 'geben'],
  ['go', 'went', 'gone', 'gehen; fahren'],
  ['grow', 'grew', 'grown', 'wachsen; anbauen; züchten'],
  ['hang', 'hung', 'hung', 'hängen'],
  ['have', 'had', 'had', 'haben'],
  ['hear', 'heard', 'heard', 'hören'],
  ['hide', 'hid', 'hidden', '(sich) verstecken'],
  ['hit', 'hit', 'hit', 'schlagen; treffen'],
  ['hold', 'held', 'held', '(fest)halten'],
  ['hurt', 'hurt', 'hurt', 'verletzen; sich wehtun'],
  ['keep', 'kept', 'kept', '(auf)bewahren; behalten'],
  ['know', 'knew', 'known', 'kennen; wissen'],
  ['lead', 'led', 'led', '(an)führen'],
  ['learn', 'learnt|learned', 'learnt|learned', 'lernen'],
  ['leave', 'left', 'left', '(ver)lassen'],
  ['let', 'let', 'let', 'lassen'],
  ['lie', 'lay', 'lain', 'liegen'],
  ['lose', 'lost', 'lost', 'verlieren'],
  ['make', 'made', 'made', 'machen; tun'],
  ['mean', 'meant', 'meant', 'bedeuten; meinen'],
  ['meet', 'met', 'met', 'treffen'],
  ['pay', 'paid', 'paid', '(be)zahlen'],
  ['put', 'put', 'put', 'legen; setzen; stellen'],
  ['read', 'read', 'read', 'lesen'],
  ['ride', 'rode', 'ridden', 'fahren; reiten'],
  ['ring', 'rang', 'rung', 'klingeln; läuten'],
  ['run', 'ran', 'run', 'laufen; rennen'],
  ['say', 'said', 'said', 'sagen'],
  ['see', 'saw', 'seen', 'sehen'],
  ['sell', 'sold', 'sold', 'verkaufen'],
  ['send', 'sent', 'sent', 'senden; verschicken'],
  ['set up', 'set up', 'set up', 'erbauen; errichten'],
  ['shoot', 'shot', 'shot', 'schießen'],
  ['show', 'showed', 'shown', 'zeigen'],
  ['sing', 'sang', 'sung', 'singen'],
  ['sink', 'sank', 'sunk', 'untergehen; sinken'],
  ['sit', 'sat', 'sat', 'sitzen'],
  ['sleep', 'slept', 'slept', 'schlafen'],
  ['smell', 'smelt|smelled', 'smelt|smelled', 'riechen; duften'],
  ['speak', 'spoke', 'spoken', 'sprechen'],
  ['spell', 'spelt|spelled', 'spelt|spelled', 'buchstabieren'],
  ['spend', 'spent', 'spent', 'ausgeben; verbringen'],
  ['stand', 'stood', 'stood', 'stehen'],
  ['steal', 'stole', 'stolen', 'stehlen'],
  ['swim', 'swam', 'swum', 'schwimmen'],
  ['take', 'took', 'taken', 'nehmen'],
  ['teach', 'taught', 'taught', 'unterrichten; lehren; beibringen'],
  ['tell', 'told', 'told', 'erzählen'],
  ['think', 'thought', 'thought', '(nach)denken; glauben'],
  ['throw', 'threw', 'thrown', 'werfen'],
  ['understand', 'understood', 'understood', 'verstehen'],
  ['wake up', 'woke up', 'woken up', '(auf)wachen; (auf)wecken'],
  ['wear', 'wore', 'worn', 'anhaben; tragen'],
  ['win', 'won', 'won', 'gewinnen; siegen'],
  ['write', 'wrote', 'written', 'schreiben'],
];
