/*
  Eingebaute Vokabellisten für Finnys Vokabeltrainer.

  Aufbau eines Eintrags:   ['Fremdwort', 'Deutsche Bedeutung']
  - Mehrere richtige Schreibweisen mit | trennen:  ['grey|gray', 'grau']
  - Das erste Fremdwort wird angezeigt und vorgesprochen.
  - lang: 'fr' (Französisch) oder 'en' (Englisch)

  Neue Listen kann man entweder hier eintragen oder in der App unter "Listen" einlesen
  (einfügen oder als .csv/.txt-Datei laden).
*/
window.VOKABELN = [

  /* ───────────────────────── FRANZÖSISCH: aus dem Schulbuch ───────────────────────── */
  { id: 'fr-u1-t1', lang: 'fr', emoji: '🗼', name: 'Unité 1 – Bonjour Paris! (Teil 1)', words: [
    ['Bonjour!', 'Guten Tag!'],
    ['et', 'und'],
    ['Viens!', 'Komm! (Aufforderung)'],
    ['papa', 'Papa'],
    ['vite', 'schnell (Adv.)'],
    ['Miaou!', 'Miau!'],
    ['Ouah, ouah!', 'Wau, wau!'],
    ['Ça va?', 'Wie geht\'s?'],
    ["je m'appelle", 'ich heiße'],
    ['Qui est-ce?', 'Wer ist das?'],
    ['Attention!', 'Achtung!, Vorsicht!'],
  ]},
  { id: 'fr-u1-t2', lang: 'fr', emoji: '🗼', name: 'Unité 1 – Bonjour Paris! (Teil 2)', words: [
    ['non', 'nein'],
    ['Pardon.', 'Entschuldigung.'],
    ['Salut!', 'Hallo! / Grüß dich! (umgangssprachlich)'],
    ['comment', 'wie? (Fragewort)'],
    ["Tu t'appelles comment?", 'Wie heißt du?'],
    ["c'est", 'das ist'],
    ['moi', 'ich (betont)'],
    ['je suis', 'ich bin'],
    ['toi', 'du (betont)'],
    ['voilà', 'da ist, da sind'],
    ['bizarre', 'komisch, merkwürdig'],
    ['un chat', 'eine Katze'],
    ['un chien', 'ein Hund'],
    ['mais', 'aber'],
    ['oui', 'ja'],
    ['bien', 'gut (Adv.)'],
    ['merci', 'danke'],
    ['ici', 'hier, hierher'],
    ['tu es', 'du bist'],
    ["de|d'", 'von, aus'],
    ['aussi', 'auch'],
  ]},
  { id: 'fr-u1-t3', lang: 'fr', emoji: '🗼', name: 'Unité 1 – Bonjour Paris! (Teil 3)', words: [
    ['super', 'super, toll'],
    ['un garçon', 'ein Junge'],
    ['une fille', 'ein Mädchen, eine Tochter'],
    ['il est', 'er ist'],
    ['elle est', 'sie ist'],
    ['fantastique', 'fantastisch, toll'],
    ['un copain|une copine', 'ein Freund / eine Freundin (umgangssprachlich)'],
    ['une dame', 'eine Dame, eine Frau'],
    ['un monsieur', 'ein Herr, ein Mann'],
    ['Strasbourg', 'Straßburg'],
    ['Nice', 'Nizza'],
    ['madame', 'Frau …'],
    ['Bof!', 'Na ja., Ach. (umgangssprachlich)'],
    ['Au revoir!', 'Auf Wiedersehen!'],
  ]},
  { id: 'fr-u2-t1', lang: 'fr', emoji: '🎒', name: 'Unité 2 – Copain, copine (Teil 1)', words: [
    ['moi aussi', 'ich auch'],
    ['toi aussi', 'du auch'],
    ['un magasin', 'ein Geschäft, ein Laden'],
    ['un journal', 'eine Zeitung'],
    ['une BD', 'ein Comic'],
    ['une affiche', 'ein Plakat, ein Poster'],
    ["Qu'est-ce que c'est?", 'Was ist das?'],
    ['à', 'in, nach (Paris)'],
    ['une maison', 'ein Haus'],
    ['une maison de la presse', 'ein Zeitschriften- und Schreibwarengeschäft'],
    ['Que fait Léo?', 'Was macht Léo?'],
    ['regarder', '(etwas) ansehen, (etwas) betrachten'],
    ['parler', 'sprechen'],
    ['avec', 'mit'],
    ['arriver', '(an)kommen'],
    ['chercher', '(jemanden / etwas) suchen'],
    ['français', 'französisch'],
    ['en français', 'auf Französisch'],
  ]},
  { id: 'fr-u2-t2', lang: 'fr', emoji: '🎒', name: 'Unité 2 – Copain, copine (Teil 2)', words: [
    ['un stylo', 'ein Füller, ein Kuli'],
    ['une gomme', 'ein Radiergummi'],
    ['un livre', 'ein Buch'],
    ['un cahier', 'ein Heft'],
    ['un crayon', 'ein Bleistift'],
    ['un truc', 'ein Ding, eine Sache (umgangssprachlich)'],
    ['écouter', '(jemandem) zuhören, (etwas) anhören'],
    ['trouver', '(jemanden / etwas) finden'],
    ['porter', '(etwas) tragen'],
    ['travailler', 'arbeiten'],
    ['dans', 'in'],
    ['une rue', 'eine Straße'],
    ['dans la rue', 'auf der Straße'],
    ['entrer', 'eintreten, hereinkommen'],
    ['euh', 'äh …'],
    ['là', 'da, dort'],
    ['Chut!', 'Pst!'],
    ['pour', 'für'],
    ['une école', 'eine Schule'],
    ['en vacances', 'in den Ferien'],
    ['Tiens!', 'Sieh mal! / Schau mal!'],
    ['une grand-mère', 'eine Großmutter'],
  ]},
  { id: 'fr-u2-t3', lang: 'fr', emoji: '🎒', name: 'Unité 2 – Copain, copine (Teil 3)', words: [
    ['il dit|elle dit', 'er sagt / sie sagt'],
    ['un carton', 'ein Karton'],
    ['un ami|une amie', 'ein Freund / eine Freundin'],
    ['Zut!', 'Mist!, Verdammt! (umgangssprachlich)'],
    ['une catastrophe', 'eine Katastrophe'],
    ['un cartable', 'eine Schultasche, ein Schulranzen'],
    ['une trousse', 'ein Federmäppchen'],
    ['une feuille', 'ein Blatt'],
    ['un classeur', 'ein Ordner'],
    ['un sac à dos', 'ein Rucksack'],
    ['être', 'sein'],
    ['on est', 'man ist, wir sind'],
    ['nous sommes', 'wir sind'],
    ['vous êtes', 'ihr seid, Sie sind'],
    ['ils sont|elles sont', 'sie sind'],
    ['devant', 'vor (örtlich)'],
  ]},
  { id: 'fr-u2-t4', lang: 'fr', emoji: '🎒', name: 'Unité 2 – Copain, copine (Teil 4)', words: [
    ['habiter', 'wohnen'],
    ['où', 'wo; wohin'],
    ['un t-shirt', 'ein T-Shirt'],
    ['aimer', '(jemanden / etwas) lieben, (jemanden / etwas) mögen'],
    ['le rugby', 'das Rugby (Ballspiel)'],
    ['le judo', 'das Judo'],
    ["Qu'est-ce que", 'Was …? (Fragewort am Satzanfang)'],
    ['le sport', 'der Sport'],
    ['la musique', 'die Musik'],
    ['un frère', 'ein Bruder'],
    ['une sœur', 'eine Schwester'],
    ['sympa', 'nett'],
    ['détester', '(jemanden / etwas) verabscheuen'],
  ]},
  { id: 'fr-u2-t5', lang: 'fr', emoji: '🎒', name: 'Unité 2 – Copain, copine (Teil 5)', words: [
    ['ça', 'das'],
    ["d'accord", 'einverstanden, o.k.'],
    ['alors', 'nun, jetzt, dann'],
    ['ouf', 'Uff!'],
    ['le rock', 'Rock, die Rockmusik'],
    ['le foot|le football', 'der Fußball (Sportart)'],
    ['un vélo', 'ein Fahrrad'],
    ['la techno', 'Techno (Musikstil)'],
    ['le rap', 'Rap (Musikstil)'],
    ['la gymnastique|la gym', 'das Turnen, die Gymnastik'],
    ['une chanson', 'ein Lied'],
    ['classique', 'klassisch'],
  ]},
  { id: 'fr-u2-dico', lang: 'fr', emoji: '🎒', name: 'Unité 2 – Mon dico personnel (Hobbys)', words: [
    ["j'aime", 'ich mag …'],
    ['je déteste', 'ich mag … überhaupt nicht'],
    ["l'ordi|l'ordinateur", 'der Computer'],
    ['la natation', 'das Schwimmen'],
    ['le cinéma', 'das Kino'],
    ['la télé|la télévision', 'das Fernsehen'],
    ['le roller', 'das Rollerskaten, das Inlinerfahren'],
    ["l'athlétisme", 'die Leichtathletik'],
    ['le basket|le basketball', 'Basketball'],
  ]},
  { id: 'fr-u2-saetze', lang: 'fr', emoji: '🎒', name: 'Unité 2 – Fragen und Antworten', words: [
    ["Qu'est-ce que c'est en français?", 'Wie heißt das auf Französisch?'],
    ["C'est un crayon.", 'Das ist ein Bleistift.'],
    ['Il porte un carton.', 'Er trägt einen Karton.'],
    ['Elle parle avec un monsieur.', 'Sie spricht mit einem Mann.'],
    ['Tu habites où?', 'Wo wohnst du?'],
    ["J'habite à Paris.", 'Ich wohne in Paris.'],
    ['Tu habites rue Nollet?', 'Wohnst du in der rue Nollet?'],
    ["Non, j'habite rue Truffaut.", 'Nein, ich wohne in der rue Truffaut.'],
    ['Tu aimes le rugby?', 'Magst du Rugby?'],
    ["Oui, et j'aime aussi le judo.", 'Ja, und ich mag auch Judo.'],
    ["Qu'est-ce que tu aimes?", 'Was magst du?'],
    ['Je déteste ça!', 'Ich mag das überhaupt nicht!'],
    ["Tu es d'accord?", 'Bist du einverstanden?'],
    ['nous sommes frère et sœur|on est frère et sœur', 'Wir sind Geschwister.'],
  ]},

  /* ───────────────────────── FRANZÖSISCH: Grundwortschatz ───────────────────────── */
  { id: 'fr-begruessung', lang: 'fr', emoji: '👋', name: 'Begrüßung & Höflichkeit', words: [
    ['bonjour', 'Guten Tag / Hallo'],
    ['salut', 'Hallo / Tschüss (unter Freunden)'],
    ['bonsoir', 'Guten Abend'],
    ['bonne nuit', 'Gute Nacht'],
    ['au revoir', 'Auf Wiedersehen'],
    ['à bientôt', 'Bis bald'],
    ['merci', 'Danke'],
    ['s\'il te plaît', 'Bitte (zu einem Freund)'],
    ['s\'il vous plaît', 'Bitte (höflich, „Sie“)'],
    ['de rien', 'Gern geschehen'],
    ['pardon', 'Entschuldigung'],
    ['oui', 'ja'],
    ['non', 'nein'],
    ['comment ça va', 'Wie geht es dir?'],
    ['ça va bien', 'Es geht mir gut'],
    ['je m\'appelle', 'Ich heiße'],
  ]},
  { id: 'fr-zahlen', lang: 'fr', emoji: '🔢', name: 'Zahlen 0–12', words: [
    ['zéro', 'null'], ['un', 'eins'], ['deux', 'zwei'], ['trois', 'drei'], ['quatre', 'vier'],
    ['cinq', 'fünf'], ['six', 'sechs'], ['sept', 'sieben'], ['huit', 'acht'], ['neuf', 'neun'], ['dix', 'zehn'],
    ['onze', 'elf'], ['douze', 'zwölf'],
  ]},
  { id: 'fr-farben', lang: 'fr', emoji: '🎨', name: 'Farben', words: [
    ['rouge', 'rot'], ['bleu', 'blau'], ['vert', 'grün'], ['jaune', 'gelb'], ['noir', 'schwarz'],
    ['blanc', 'weiß'], ['orange', 'orange'], ['rose', 'rosa'], ['gris', 'grau'], ['marron', 'braun'], ['violet', 'lila'],
  ]},
  { id: 'fr-tiere', lang: 'fr', emoji: '🐾', name: 'Tiere', words: [
    ['le chat', 'die Katze'], ['le chien', 'der Hund'], ['l\'oiseau', 'der Vogel'], ['le poisson', 'der Fisch'],
    ['le cheval', 'das Pferd'], ['la vache', 'die Kuh'], ['le lapin', 'das Kaninchen'], ['la souris', 'die Maus'],
    ['le cochon', 'das Schwein'], ['l\'éléphant', 'der Elefant'], ['le lion', 'der Löwe'], ['la grenouille', 'der Frosch'],
  ]},
  { id: 'fr-familie', lang: 'fr', emoji: '👨‍👩‍👧', name: 'Familie & Freunde', words: [
    ['la famille', 'die Familie'], ['la mère', 'die Mutter'], ['le père', 'der Vater'], ['le frère', 'der Bruder'],
    ['la sœur', 'die Schwester'], ['la grand-mère', 'die Großmutter'], ['le grand-père', 'der Großvater'],
    ['l\'enfant', 'das Kind'], ['le bébé', 'das Baby'], ['l\'ami', 'der Freund'], ['l\'amie', 'die Freundin'],
  ]},
  { id: 'fr-schule', lang: 'fr', emoji: '🎒', name: 'Schule', words: [
    ['l\'école', 'die Schule'], ['la classe', 'die Klasse'], ['le professeur', 'der Lehrer'], ['le livre', 'das Buch'],
    ['le cahier', 'das Heft'], ['le stylo', 'der Kugelschreiber'], ['le crayon', 'der Bleistift'],
    ['la trousse', 'das Mäppchen'], ['le cartable', 'der Schulranzen'], ['la table', 'der Tisch'],
    ['la chaise', 'der Stuhl'], ['le sac', 'die Tasche'],
  ]},
  { id: 'fr-essen', lang: 'fr', emoji: '🥖', name: 'Essen & Trinken', words: [
    ['le pain', 'das Brot'], ['le fromage', 'der Käse'], ['le lait', 'die Milch'], ['l\'eau', 'das Wasser'],
    ['la pomme', 'der Apfel'], ['la banane', 'die Banane'], ['le gâteau', 'der Kuchen'], ['le chocolat', 'die Schokolade'],
    ['le jus d\'orange', 'der Orangensaft'], ['la glace', 'das Eis'], ['le petit déjeuner', 'das Frühstück'],
  ]},

  /* ───────────────────────── ENGLISCH ───────────────────────── */
  { id: 'en-greetings', lang: 'en', emoji: '👋', name: 'Greetings', words: [
    ['hello', 'Hallo'], ['hi', 'Hi / Hallo'], ['good morning', 'Guten Morgen'], ['good afternoon', 'Guten Tag (nachmittags)'],
    ['good evening', 'Guten Abend'], ['good night', 'Gute Nacht'], ['goodbye', 'Auf Wiedersehen'], ['see you', 'Bis später'],
    ['thank you', 'Danke'], ['please', 'Bitte'], ['sorry', 'Entschuldigung'], ['yes', 'ja'], ['no', 'nein'],
    ['how are you', 'Wie geht es dir?'], ['I\'m fine', 'Mir geht es gut'], ['my name is', 'Ich heiße'],
  ]},
  { id: 'en-numbers', lang: 'en', emoji: '🔢', name: 'Numbers 0–10', words: [
    ['zero', 'null'], ['one', 'eins'], ['two', 'zwei'], ['three', 'drei'], ['four', 'vier'], ['five', 'fünf'],
    ['six', 'sechs'], ['seven', 'sieben'], ['eight', 'acht'], ['nine', 'neun'], ['ten', 'zehn'],
  ]},
  { id: 'en-colours', lang: 'en', emoji: '🎨', name: 'Colours', words: [
    ['red', 'rot'], ['blue', 'blau'], ['green', 'grün'], ['yellow', 'gelb'], ['black', 'schwarz'], ['white', 'weiß'],
    ['orange', 'orange'], ['pink', 'rosa'], ['grey|gray', 'grau'], ['brown', 'braun'], ['purple', 'lila'],
  ]},
  { id: 'en-animals', lang: 'en', emoji: '🐾', name: 'Animals', words: [
    ['cat', 'die Katze'], ['dog', 'der Hund'], ['bird', 'der Vogel'], ['fish', 'der Fisch'], ['horse', 'das Pferd'],
    ['cow', 'die Kuh'], ['rabbit', 'das Kaninchen'], ['mouse', 'die Maus'], ['pig', 'das Schwein'],
    ['elephant', 'der Elefant'], ['lion', 'der Löwe'], ['frog', 'der Frosch'],
  ]},
  { id: 'en-family', lang: 'en', emoji: '👨‍👩‍👧', name: 'Family & Friends', words: [
    ['family', 'die Familie'], ['mother', 'die Mutter'], ['father', 'der Vater'], ['brother', 'der Bruder'],
    ['sister', 'die Schwester'], ['grandmother', 'die Großmutter'], ['grandfather', 'der Großvater'],
    ['child', 'das Kind'], ['baby', 'das Baby'], ['friend', 'der Freund / die Freundin'], ['parents', 'die Eltern'],
  ]},
  { id: 'en-school', lang: 'en', emoji: '🎒', name: 'School', words: [
    ['school', 'die Schule'], ['class', 'die Klasse'], ['teacher', 'der Lehrer'], ['book', 'das Buch'],
    ['exercise book', 'das Heft'], ['pen', 'der Kugelschreiber'], ['pencil', 'der Bleistift'],
    ['pencil case', 'das Mäppchen'], ['school bag', 'der Schulranzen'], ['table', 'der Tisch'],
    ['chair', 'der Stuhl'], ['bag', 'die Tasche'],
  ]},
  { id: 'en-food', lang: 'en', emoji: '🍎', name: 'Food & Drink', words: [
    ['bread', 'das Brot'], ['cheese', 'der Käse'], ['milk', 'die Milch'], ['water', 'das Wasser'],
    ['apple', 'der Apfel'], ['banana', 'die Banane'], ['cake', 'der Kuchen'], ['chocolate', 'die Schokolade'],
    ['orange juice', 'der Orangensaft'], ['ice cream', 'das Eis'], ['breakfast', 'das Frühstück'],
  ]},
];
